apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: hello-fastapi
  newName: luizmario/hello-fastapi-k8s
  newTag: 38c1b908e42fc488834c091850cd3574329a722a
